### ISSUE TITLE
Unable To Get Token Via OAuth

### ISSUE THREAD

**Issue by bentleycook** [jchrom/trelloR#11] opened 2017-05-31 19:53 UTC
Originally reported here: 
https://community.atlassian.com/t5/Trello-questions/500-Internal-Server-Error/qaq-p/591559?posted=592631#U592631

Original text:
```
I'm trying to import the data from Trello in R using the trelloR package. Everything works fine when using public boards.
library(trelloR)
url = "https://trello.com/b/nC8QJJoZ/trello-development-roadmap"
bid = get_id_board(url)
cards = get_board_cards(bid, limit = 5)
Problem arise when I want to connect to my private boards
token <- trello_get_token(key = Sys.getenv("TRELLO_KEY"), secret = Sys.getenv("TRELLO_SECRET"))
Error in init_oauth1.0(self$endpoint, self$app, permission = self$params$permission, : Internal Server Error (HTTP 500).
Sys.getenv("TRELLO_KEY") and Sys.getenv("TRELLO_SECRET") are environment variables that hold the api key and secret.
```

I'm not incredibly familiar with R but after digging into the docs for [`oauth_endpoint`](https://www.rdocumentation.org/packages/httr/versions/1.2.1/topics/oauth_endpoint) I saw that this package was passing in explicit parameters.

Perhaps [this](https://github.com/jchrom/trelloR/blob/b0c26875e096cc96630743628ac88a5cb9e5d737/R/trello_get_token.R#L32) section could be updated to:
```
    trello.urls = oauth_endpoint(
        request = "https://trello.com/1/OAuthGetRequestToken",
        authorize = "https://trello.com/1/OAuthAuthorizeToken",
        access = "https://trello.com/1/OAuthGetAccessToken")
```

**Comment by jchrom** [comment] 2017-06-03 07:26
Right, naming arguments is best practice when writing functions. Do you think that this causes the problem Thierry is reporting thou? I cannot really test this since I was not able to reproduce Thierry's problem.

**Comment by jchrom** [comment] 2017-09-12 20:54
Closing as I could not replicate.

**Closed as completed by jchrom** 2017-09-12 20:54 UTC
